/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Inicio.java
 *
 * Created on 2/10/2009, 11:40:23 AM
 */

/**
 *
 * @author Estudiante
 */
public class Inicio extends javax.swing.JFrame {

    /** Creates new form Inicio */
    public Inicio() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        MURA = new MURA();
        Con_friccion = new MURAF();
        Uniforme = new MUR();
        caida_Libre1 = new Caida_Libre();
        semi_Parabolico1 = new Semi_Parabolico();
        parabolico1 = new Parabolico();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIMULACIÓN DE LABORATORIOS FISICOS SOBRE MOVIMIENTO");
        setResizable(false);

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 0));
        jTabbedPane1.setFont(new java.awt.Font("Vivaldi", 1, 18));
        jTabbedPane1.addTab("Uniforme Acelerado", MURA);
        jTabbedPane1.addTab("Fricción", Con_friccion);
        jTabbedPane1.addTab("Uniforme", Uniforme);
        jTabbedPane1.addTab("Caida Libre", caida_Libre1);
        jTabbedPane1.addTab("MovimientoSemi Parabólico", semi_Parabolico1);
        jTabbedPane1.addTab("Moivimiento Parabólico", parabolico1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 889, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-897)/2, (screenSize.height-550)/2, 897, 550);
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private MURAF Con_friccion;
    private MURA MURA;
    private MUR Uniforme;
    private Caida_Libre caida_Libre1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private Parabolico parabolico1;
    private Semi_Parabolico semi_Parabolico1;
    // End of variables declaration//GEN-END:variables

}
