/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MURAF.java
 *
 * Created on 02-oct-2009, 16:02:24
 */
import Semi_parabolico.Alaska;
/**
 *
 * @author José Eduardo Pérez C
 */
public class Semi_Parabolico extends javax.swing.JPanel {

    /** Creates new form MURAF */
    public Semi_Parabolico() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 600));

        jButton1.setFont(new java.awt.Font("Agency FB", 1, 18));
        jButton1.setText("Ver graficas");

        jButton2.setFont(new java.awt.Font("Agency FB", 1, 18));
        jButton2.setText("Ir a simulación");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 14));
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("\nEs tambien llamado el movimiento de media parábola o semiparabólico (lanzamiento horizontal) \nse puede considerar como la composición de un avance horizontal rectilíneo uniforme y la caída libre.\nEl movimiento semi parabólico es un tipo de movimiento parabòlico al igual que el movimiento parabólico\ncompleto.\n\nPor ende este tipo de movimiento se rige por las mismas ecuaciones del movimiento parabólico y que sus\ngraficas sean las mismas tambien. Ademas de esto podemos decir que, para facilitar el estudio del \nmovimiento de un proyectil, frecuentemente este se descompone en las direcciones horizontal y vertical. \nEn la dirección horizontal el movimiento del proyectil es rectilíneo y uniforme ya que en esa dirección \nla acción de la gravedad es nula y consecuente, la aceleración también lo es. En la dirección vertical,\nsobre el proyectil actúa la fuerza de gravedad que hace que el movimiento sea rectilíneo uniformemente \nacelerado, con aceleración constante.\n\n\nEn la simulacion de este tipo de movimiento se vera las similitudes y la pequeña diferencia con el \nmovimiento parabólico normal\n");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jButton1)
                        .addGap(110, 110, 110)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Alaska frame = new Alaska();
        frame.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
